-- Bronze: Vaastav Players (Snapshot data per season from players_raw.parquet)
-- This table stores the full player snapshot data from Vaastav for each season

CREATE TABLE IF NOT EXISTS bronze_vaastav_players (
    id INTEGER NOT NULL,
    web_name TEXT,
    first_name TEXT,
    second_name TEXT,
    team INTEGER,
    element_type INTEGER,
    now_cost INTEGER,
    total_points INTEGER,
    selected_by_percent TEXT,
    status TEXT,
    code INTEGER,
    photo TEXT,
    points_per_game TEXT,
    form TEXT,
    value_season TEXT,
    value_form TEXT,
    transfers_in INTEGER,
    transfers_out INTEGER,
    transfers_in_event INTEGER,
    transfers_out_event INTEGER,
    news TEXT,
    chance_of_playing_next_round INTEGER,
    chance_of_playing_this_round INTEGER,
    cost_change_event INTEGER,
    cost_change_event_fall INTEGER,
    cost_change_start INTEGER,
    cost_change_start_fall INTEGER,
    dreamteam_count INTEGER,
    ep_next TEXT,
    ep_this TEXT,
    event_points INTEGER,
    in_dreamteam BOOLEAN,
    removed BOOLEAN,
    special BOOLEAN,
    squad_number INTEGER,
    team_code INTEGER,
    minutes INTEGER,
    goals_scored INTEGER,
    assists INTEGER,
    clean_sheets INTEGER,
    goals_conceded INTEGER,
    own_goals INTEGER,
    penalties_saved INTEGER,
    penalties_missed INTEGER,
    yellow_cards INTEGER,
    red_cards INTEGER,
    saves INTEGER,
    bonus INTEGER,
    bps INTEGER,
    influence TEXT,
    creativity TEXT,
    threat TEXT,
    ict_index TEXT,
    starts INTEGER,
    expected_goals TEXT,
    expected_assists TEXT,
    expected_goal_involvements TEXT,
    expected_goals_conceded TEXT,
    birth_date TEXT,
    can_select BOOLEAN,
    can_transact BOOLEAN,
    clean_sheets_per_90 TEXT,
    corners_and_indirect_freekicks_order INTEGER,
    corners_and_indirect_freekicks_text TEXT,
    creativity_rank TEXT,
    creativity_rank_type INTEGER,
    direct_freekicks_order INTEGER,
    direct_freekicks_text TEXT,
    expected_assists_per_90 TEXT,
    expected_goal_involvements_per_90 TEXT,
    expected_goals_conceded_per_90 TEXT,
    expected_goals_per_90 TEXT,
    form_rank TEXT,
    form_rank_type INTEGER,
    goals_conceded_per_90 TEXT,
    has_temporary_code BOOLEAN,
    ict_index_rank TEXT,
    ict_index_rank_type INTEGER,
    influence_rank TEXT,
    influence_rank_type INTEGER,
    mng_clean_sheets INTEGER,
    mng_draw INTEGER,
    mng_goals_scored INTEGER,
    mng_loss INTEGER,
    mng_underdog_draw INTEGER,
    mng_underdog_win INTEGER,
    mng_win INTEGER,
    news_added TEXT,
    now_cost_rank TEXT,
    now_cost_rank_type INTEGER,
    opta_code TEXT,
    penalties_order INTEGER,
    penalties_text TEXT,
    points_per_game_rank TEXT,
    points_per_game_rank_type INTEGER,
    region INTEGER,
    selected_rank TEXT,
    selected_rank_type INTEGER,
    starts_per_90 TEXT,
    team_join_date TEXT,
    threat_rank TEXT,
    threat_rank_type INTEGER,
    saves_per_90 TEXT,
    season TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    PRIMARY KEY (id, season)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_bronze_vaastav_players_season ON bronze_vaastav_players(season);
CREATE INDEX IF NOT EXISTS idx_bronze_vaastav_players_team ON bronze_vaastav_players(team) WHERE team IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bronze_vaastav_players_element_type ON bronze_vaastav_players(element_type) WHERE element_type IS NOT NULL;